const PUT_DRIVER_DATA = 'PUT_DRIVER_DATA';
const PUT_DRIVER_DATA_PENDING = `${PUT_DRIVER_DATA}_PENDING`;
const PUT_DRIVER_DATA_REJECTED = `${PUT_DRIVER_DATA}_REJECTED`;
const PUT_DRIVER_DATA_FULFILLED = `${PUT_DRIVER_DATA}_FULFILLED`;

const ActionTypes = {
    PUT_DRIVER_DATA,
    PUT_DRIVER_DATA_REJECTED,
    PUT_DRIVER_DATA_FULFILLED,
    PUT_DRIVER_DATA_PENDING
};

export default ActionTypes;
